apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: virtapp
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: local
    repoURL: https://github.com/virtapp/deployment.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
