apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portal
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: portal
    repoURL: https://github.com/virtapp/deployment.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
